export const nigerianUniversities = {
  "Federal Universities": [
    "Abubakar Tafawa Balewa University, Bauchi",
    "Ahmadu Bello University, Zaria",
    "Bayero University, Kano",
    "Federal University Gashua, Yobe",
    "Federal University of Petroleum Resources, Effurun",
    "Federal University of Technology, Akure",
    "Federal University of Technology, Minna",
    "Federal University of Technology, Owerri",
    "Federal University, Dutse, Jigawa State",
    "Federal University, Dutsin-Ma, Katsina",
    "Federal University, Kashere, Gombe State",
    "Federal University, Lafia, Nasarawa State",
    "Federal University, Lokoja, Kogi State",
    "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
    "Federal University, Otuoke, Bayelsa",
    "Federal University, Oye-Ekiti, Ekiti State",
    "Federal University, Wukari, Taraba State",
    "Federal University, Birnin Kebbi",
    "Federal University, Gusau, Zamfara",
    "Michael Okpara University of Agriculture, Umudike",
    "Modibbo Adama University",
    "National Open University of Nigeria, Abuja",
    "Nigeria Police Academy, Wudil",
    "Nigerian Defence Academy, Kaduna",
    "Nnamdi Azikiwe University, Awka",
    "Obafemi Awolowo University, Ile-Ife",
    "University of Abuja, Gwagwalada",
    "Federal University of Agriculture, Abeokuta",
    "Joseph Sarwuan Tarka University, Makurdi",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Nigeria, Nsukka",
    "University of Port Harcourt",
    "University of Uyo",
    "Usmanu Danfodiyo University, Sokoto",
    "Nigerian Maritime University, Delta State",
    "Air Force Institute of Technology, Kaduna",
    "Nigerian Army University, Biu",
    "Federal University of Health Sciences, Otukpo",
    "Federal University of Agriculture, Zuru, Kebbi State",
    "Federal University of Technology, Babura, Jigawa State",
    "Federal University of Technology, Ikot Abasi",
    "Federal University of Health Sciences, Azare",
    "Federal University of Health Sciences, Ila Orangun",
    "David Umahi Federal University of Health Sciences",
    "Admiralty University, Delta State",
    "Federal University of Transportation, Daura, Katsina",
    "African Aviation and Aerospace University",
    "National University of Science and Technology, Abuja",
    "Federal University of Agriculture, Bassam-Biri, Bayelsa",
    "Federal University of Health Sciences, Kwale, Delta State",
    "Federal University of Health Sciences, Katsina",
    "Federal University of Agriculture, Mubi",
    "Federal University of Education, Zaria, Kaduna State",
    "Alvan Ikoku Federal University of Education",
    "Federal University of Education, Kano",
    "Adeyemi University of Education, Ondo",
  ],
  "State Universities": [
    "Abia State University, Uturu",
    "Adamawa State University, Mubi",
    "Adekunle Ajasin University, Akungba",
    "Akwa Ibom State University, Ikot Akpaden",
    "Ambrose Alli University, Ekpoma",
    "Chukwuemeka Odumegwu Ojukwu University, Uli",
    "Bauchi State University, Gadau",
    "Benue State University, Makurdi",
    "Yobe State University, Damaturu",
    "Cross River State University of Technology, Calabar",
    "Delta State University, Abraka",
    "Ebonyi State University, Abakaliki",
    "Ekiti State University",
    "Enugu State University of Science and Technology",
    "Gombe State University, Gombe",
    "Ibrahim Badamasi Babangida University, Lapai",
    "Ignatius Ajuru University of Education, Rumuolumeni",
    "Imo State University, Owerri",
    "Sule Lamido University, Kafin Hausa, Jigawa",
    "Kaduna State University, Kaduna",
    "Kano University of Science & Technology, Wudil",
    "Kebbi State University of Science and Technology, Aliero",
    "Prince Abubakar Audu University, Anyigba",
    "Kwara State University, Ilorin",
    "Ladoke Akintola University of Technology, Ogbomoso",
    "Ondo State University of Science and Technology, Okitipupa",
    "Rivers State University",
    "Olabisi Onabanjo University, Ago Iwoye",
    "Lagos State University, Ojo",
    "Niger Delta University, Yenagoa",
    "Nasarawa State University, Keffi",
    "Plateau State University, Bokkos",
    "Tai Solarin University of Education, Ijebu Ode",
    "Umaru Musa Yar'Adua University, Katsina",
    "Osun State University, Osogbo",
    "Taraba State University, Jalingo",
    "Sokoto State University",
    "Yusuf Maitama Sule University, Kano",
    "First Technical University, Ibadan",
    "Ondo State University of Medical Sciences",
    "Edo State University, Uzairue",
    "Kingsley Ozumba Mbadiwe University, Ogboko, Imo State",
    "University of Africa, Toru-Orua, Bayelsa State",
    "Borno State University, Maiduguri",
    "Moshood Abiola University of Science and Technology, Abeokuta",
    "Gombe State University of Science and Technology",
    "Zamfara State University",
    "Bayelsa Medical University",
    "University of Agriculture and Environmental Sciences, Umuagwo",
    "Confluence University of Science and Technology, Osara, Kogi",
    "University of Delta, Agbor",
    "Delta State University of Science and Technology, Ozoro",
    "Dennis Osadebe University, Asaba",
    "Bamidele Olumilua University of Science and Technology, Ikere",
    "Lagos State University of Education, Ijanikin",
    "Lagos State University of Science and Technology, Ikorodu",
    "Shehu Shagari University of Education, Sokoto",
    "State University of Medical and Applied Sciences, Igbo-Eno, Enugu",
    "University of Ilesa, Osun State",
    "Emmanuel Alayande University of Education, Oyo",
    "Sa'adatu Rimi University of Education",
    "Kogi State University, Kabba",
    "AbdulKadir Kure University, Minna, Niger State",
  ],
  "Private Universities": [
    "Achievers University, Owo",
    "Adeleke University, Ede",
    "Afe Babalola University, Ado-Ekiti",
    "Ajayi Crowther University, Ibadan",
    "Al-Hikmah University, Ilorin",
    "Al-Qalam University, Katsina",
    "American University of Nigeria, Yola",
    "Augustine University",
    "Babcock University, Ilishan-Remo",
    "Baze University",
    "Bells University of Technology, Otta",
    "Benson Idahosa University, Benin City",
    "Bingham University, New Karu",
    "Bowen University, Iwo",
    "Caleb University, Lagos",
    "Caritas University, Enugu",
    "Chrisland University",
    "Covenant University, Ota",
    "Crawford University, Igbesa",
    "Crescent University",
    "Edwin Clark University, Kiagbodo",
    "Elizade University, Ilara-Mokin",
    "Evangel University, Akaeze",
    "Fountain University, Oshogbo",
    "Godfrey Okoye University, Ugwuomu-Nike",
    "Gregory University, Uturu",
    "Hallmark University, Ijebu Itele",
    "Hezekiah University, Umudi",
    "Igbinedion University, Okada",
    "Joseph Ayo Babalola University, Ikeji-Arakeji",
    "Kings University, Ode-Omu",
    "Kwararafa University, Wukari",
    "Landmark University, Omu-Aran",
    "Lead City University, Ibadan",
    "Madonna University, Okija",
    "McPherson University, Seriki Sotayo",
    "Michael & Cecilia Ibru University",
    "Mountain Top University",
    "Nile University of Nigeria, Abuja",
    "Novena University, Ogume",
    "Obong University, Obong Ntak",
    "Oduduwa University, Ipetumodu",
    "Pan-Atlantic University, Lagos",
    "Paul University, Awka",
    "Redeemer's University, Ede",
    "Renaissance University, Enugu",
    "Rhema University, Obeama-Asa",
    "Ritman University, Ikot Ekpene",
    "Salem University, Lokoja",
    "Glorious Vision University, Ogwa",
    "Southwestern University, Oku Owa",
    "Summit University, Offa",
    "Tansian University, Umunya",
    "University of Mkar, Mkar",
    "Veritas University, Abuja",
    "Wellspring University, Evbuobanosa",
    "Wesley University, Ondo",
    "Western Delta University, Oghara",
    "Christopher University, Mowe",
    "Kola Daisi University, Ibadan",
    "Anchor University, Ayobo, Lagos",
    "Dominican University, Ibadan",
    "Legacy University, Okija",
    "Arthur Jarvis University, Akpoyubo",
    "Ojaja University, Eiyenkorin",
    "Coal City University, Enugu",
    "Clifford University, Owerrinta",
    "Spiritan University, Nneochi",
    "Precious Cornerstone University, Oyo",
    "PAMO University of Medical Sciences, Port Harcourt",
    "Atiba University, Oyo",
    "Eko University of Medical and Health Sciences, Ijanikin",
    "Skyline University, Kano",
    "Greenfield University, Kaduna",
    "Dominion University, Ibadan",
    "Trinity University, Ogun State",
    "Westland University, Iwo",
    "Topfaith University, Mkpatak",
    "Thomas Adewumi University, Oko-Irese",
    "Maranatha University, Mgbidi",
    "Ave Maria University, Piyanko",
    "Al-Istiqama University, Sumaila",
    "Mudiame University, Irrua",
    "Havilla University, Nde-Ikom",
    "Claretian University of Nigeria, Nekede",
    "NOK University, Kachia",
    "Karl-Kumm University, Vom",
    "James Hope University, Lagos",
    "Maryam Abacha American University of Nigeria, Kano",
    "Capital City University, Kano",
    "Ahman Pategi University, Kwara",
    "University of Offa, Kwara",
    "Mewar International University, Masaka",
    "Edusoko University, Bida",
    "Philomath University, Kuje, Abuja",
    "Khadija University, Majia",
    "Anan University, Kwall",
    "North Eastern University, Gombe",
    "Al-Ansar University, Maiduguri",
    "Margaret Lawrence University, Umunede",
    "Khalifa Isyaku Rabiu University, Kano",
    "Sports University, Idumuje-Ugboko",
    "Baba Ahmed University, Kano",
    "Saisa University of Medical Sciences and Technology",
    "Nigerian British University, Asa",
    "Peter University, Achina-Onneh",
    "Newgate University, Minna",
    "European University of Nigeria, Duboyi",
    "NorthWest University, Sokoto",
    "Rayhaan University, Kebbi",
    "Muhammad Kamalud University, Kwara",
    "Sam Maris University, Ondo",
    "Aletheia University, Ago-Iwoye",
    "Lux Mundi University, Umuahia",
    "Maduka University, Ekwegbe",
    "PeaceLand University, Enugu",
    "Amadeus University, Amizi",
    "Vision University, Ikogbo",
    "Azman University, Kano",
    "Huda University, Gusau",
    "Franco British International University, Kaduna",
    "Canadian University of Nigeria, Abuja",
    "Gerar University of Medical Sciences, Imope Ijebu",
    "British Canadian University, Obufu",
    "Hensard University, Toru-Orua",
    "Amaj University, Kwali",
    "Phoenix University, Agwada",
    "Wigwe University, Isiokpo",
    "Hillside University of Science and Technology, Okemisi",
    "University on the Niger, Umunya",
    "Elrazi Medical University, Yargaya",
    "Venite University, Iloro-Ekiti",
    "Shanahan University, Onitsha",
    "The Duke Medical University, Calabar",
    "Mercy Medical University, Iwo",
    "Cosmopolitan University, Abuja",
    "Miva Open University, Abuja",
    "Iconic Open University, Sokoto",
    "West Midlands Open University, Ibadan",
    "Al-Muhibbah Open University, Abuja",
    "El-Amin University, Minna",
    "College of Petroleum and Energy Studies, Kaduna",
    "Jewel University, Gombe",
    "Prime University, Kuje, Abuja",
    "Nigerian University of Technology and Management, Apapa",
    "Al-Bayan University, Ankpa",
    "Lighthouse University, Evbobanosa",
    "African University of Economics, Abuja",
  ],
  "Other": ["Other / Not listed"],
};