
export const nigerianCourses = {
  "Sciences": [
    "Biochemistry",
    "Biology",
    "Botany",
    "Chemistry",
    "Computer Science",
    "Cyber Security",
    "Data Science",
    "Environmental Science",
    "Geology",
    "Industrial Chemistry",
    "Information Technology",
    "Marine Biology",
    "Mathematics",
    "Microbiology",
    "Physics",
    "Software Engineering",
    "Statistics",
    "Zoology",
  ],
  "Engineering & Technology": [
    "Agricultural Engineering",
    "Chemical Engineering",
    "Civil Engineering",
    "Computer Engineering",
    "Electrical/Electronics Engineering",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Metallurgical Engineering",
    "Petroleum Engineering",
    "Production Engineering",
    "Telecommunications Engineering",
  ],
  "Medicine & Health Sciences": [
    "Anatomy",
    "Dentistry",
    "Human Physiology",
    "Medical Laboratory Science",
    "Medicine and Surgery (MBBS)",
    "Nursing Science",
    "Nutrition and Dietetics",
    "Optometry",
    "Pharmacy",
    "Physiotherapy",
    "Public Health",
    "Radiography",
    "Veterinary Medicine",
  ],
  "Social Sciences": [
    "Economics",
    "Geography",
    "International Relations",
    "Mass Communication",
    "Peace and Conflict Studies",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Social Work",
    "Sociology",
  ],
  "Management & Business": [
    "Accounting",
    "Actuarial Science",
    "Banking and Finance",
    "Business Administration",
    "Entrepreneurship",
    "Human Resource Management",
    "Insurance",
    "Marketing",
    "Office Technology and Management",
    "Taxation",
  ],
  "Arts & Humanities": [
    "English Language",
    "French",
    "History and International Studies",
    "Linguistics",
    "Literature in English",
    "Music",
    "Philosophy",
    "Religious Studies",
    "Theatre and Film Studies",
  ],
  "Law": [
    "Law (LLB)",
  ],
  "Education": [
    "Adult Education",
    "Business Education",
    "Early Childhood Education",
    "Educational Administration and Planning",
    "Guidance and Counselling",
    "Human Kinetics and Health Education",
    "Library and Information Science",
    "Science Education",
    "Vocational and Technical Education",
  ],
  "Agriculture": [
    "Agricultural Economics",
    "Agricultural Extension",
    "Animal Science",
    "Crop Science",
    "Fisheries and Aquaculture",
    "Food Science and Technology",
    "Forestry and Wildlife",
    "Soil Science",
  ],
  "Environmental Sciences & Architecture": [
    "Architecture",
    "Building Technology",
    "Estate Management",
    "Quantity Surveying",
    "Surveying and Geoinformatics",
    "Urban and Regional Planning",
  ],
};