export const nigerianUniversities = {
  "Federal Universities": [
    "Abubakar Tafawa Balewa University, Bauchi",
    "Adeyemi University of Education, Ondo",
    "Admiralty University, Delta State",
    "African Aviation and Aerospace University",
    "Ahmadu Bello University, Zaria",
    "Air Force Institute of Technology, Kaduna",
    "Alex Ekwueme University, Ndufu-Alike, Ebonyi State",
    "Alvan Ikoku Federal University of Education",
    "Bayero University, Kano",
    "David Umahi Federal University of Health Sciences",
    "Federal University Gashua, Yobe",
    "Federal University of Agriculture, Abeokuta",
    "Federal University of Agriculture, Bassam-Biri, Bayelsa",
    "Federal University of Agriculture, Mubi",
    "Federal University of Agriculture, Zuru, Kebbi State",
    "Federal University of Education, Kano",
    "Federal University of Education, Zaria, Kaduna State",
    "Federal University of Health Sciences, Azare",
    "Federal University of Health Sciences, Ila Orangun",
    "Federal University of Health Sciences, Katsina",
    "Federal University of Health Sciences, Kwale, Delta State",
    "Federal University of Health Sciences, Otukpo",
    "Federal University of Petroleum Resources, Effurun",
    "Federal University of Technology, Akure",
    "Federal University of Technology, Babura, Jigawa State",
    "Federal University of Technology, Ikot Abasi",
    "Federal University of Technology, Minna",
    "Federal University of Technology, Owerri",
    "Federal University of Transportation, Daura, Katsina",
    "Federal University, Birnin Kebbi",
    "Federal University, Dutse, Jigawa State",
    "Federal University, Dutsin-Ma, Katsina",
    "Federal University, Gusau, Zamfara",
    "Federal University, Kashere, Gombe State",
    "Federal University, Lafia, Nasarawa State",
    "Federal University, Lokoja, Kogi State",
    "Federal University, Otuoke, Bayelsa",
    "Federal University, Oye-Ekiti, Ekiti State",
    "Federal University, Wukari, Taraba State",
    "Joseph Sarwuan Tarka University, Makurdi",
    "Michael Okpara University of Agriculture, Umudike",
    "Modibbo Adama University",
    "National Open University of Nigeria, Abuja",
    "National University of Science and Technology, Abuja",
    "Nigeria Police Academy, Wudil",
    "Nigerian Army University, Biu",
    "Nigerian Defence Academy, Kaduna",
    "Nigerian Maritime University, Delta State",
    "Nnamdi Azikiwe University, Awka",
    "Obafemi Awolowo University, Ile-Ife",
    "University of Abuja, Gwagwalada",
    "University of Benin",
    "University of Calabar",
    "University of Ibadan",
    "University of Ilorin",
    "University of Jos",
    "University of Lagos",
    "University of Maiduguri",
    "University of Nigeria, Nsukka",
    "University of Port Harcourt",
    "University of Uyo",
    "Usmanu Danfodiyo University, Sokoto",
  ],
  "State Universities": [
    "AbdulKadir Kure University, Minna, Niger State",
    "Abia State University, Uturu",
    "Adamawa State University, Mubi",
    "Adekunle Ajasin University, Akungba",
    "Akwa Ibom State University, Ikot Akpaden",
    "Ambrose Alli University, Ekpoma",
    "Bamidele Olumilua University of Science and Technology, Ikere",
    "Bauchi State University, Gadau",
    "Bayelsa Medical University",
    "Benue State University, Makurdi",
    "Borno State University, Maiduguri",
    "Chukwuemeka Odumegwu Ojukwu University, Uli",
    "Confluence University of Science and Technology, Osara, Kogi",
    "Cross River State University of Technology, Calabar",
    "Delta State University of Science and Technology, Ozoro",
    "Delta State University, Abraka",
    "Dennis Osadebe University, Asaba",
    "Ebonyi State University, Abakaliki",
    "Edo State University, Uzairue",
    "Ekiti State University",
    "Emmanuel Alayande University of Education, Oyo",
    "Enugu State University of Science and Technology",
    "First Technical University, Ibadan",
    "Gombe State University of Science and Technology",
    "Gombe State University, Gombe",
    "Ibrahim Badamasi Babangida University, Lapai",
    "Ignatius Ajuru University of Education, Rumuolumeni",
    "Imo State University, Owerri",
    "Kaduna State University, Kaduna",
    "Kano University of Science & Technology, Wudil",
    "Kebbi State University of Science and Technology, Aliero",
    "Kingsley Ozumba Mbadiwe University, Ogboko, Imo State",
    "Kogi State University, Kabba",
    "Kwara State University, Ilorin",
    "Ladoke Akintola University of Technology, Ogbomoso",
    "Lagos State University of Education, Ijanikin",
    "Lagos State University of Science and Technology, Ikorodu",
    "Lagos State University, Ojo",
    "Moshood Abiola University of Science and Technology, Abeokuta",
    "Nasarawa State University, Keffi",
    "Niger Delta University, Yenagoa",
    "Olabisi Onabanjo University, Ago Iwoye",
    "Ondo State University of Medical Sciences",
    "Ondo State University of Science and Technology, Okitipupa",
    "Osun State University, Osogbo",
    "Plateau State University, Bokkos",
    "Prince Abubakar Audu University, Anyigba",
    "Rivers State University",
    "Sa'adatu Rimi University of Education",
    "Shehu Shagari University of Education, Sokoto",
    "Sokoto State University",
    "State University of Medical and Applied Sciences, Igbo-Eno, Enugu",
    "Sule Lamido University, Kafin Hausa, Jigawa",
    "Tai Solarin University of Education, Ijebu Ode",
    "Taraba State University, Jalingo",
    "Umaru Musa Yar'Adua University, Katsina",
    "University of Africa, Toru-Orua, Bayelsa State",
    "University of Agriculture and Environmental Sciences, Umuagwo",
    "University of Delta, Agbor",
    "University of Ilesa, Osun State",
    "Yobe State University, Damaturu",
    "Yusuf Maitama Sule University, Kano",
    "Zamfara State University",
  ],
  "Private Universities": [
    "Achievers University, Owo",
    "Adeleke University, Ede",
    "Afe Babalola University, Ado-Ekiti",
    "African University of Economics, Abuja",
    "Ahman Pategi University, Kwara",
    "Ajayi Crowther University, Ibadan",
    "Al-Ansar University, Maiduguri",
    "Al-Bayan University, Ankpa",
    "Al-Hikmah University, Ilorin",
    "Al-Istiqama University, Sumaila",
    "Al-Muhibbah Open University, Abuja",
    "Al-Qalam University, Katsina",
    "Aletheia University, Ago-Iwoye",
    "Amadeus University, Amizi",
    "Amaj University, Kwali",
    "American University of Nigeria, Yola",
    "Anan University, Kwall",
    "Anchor University, Ayobo, Lagos",
    "Arthur Jarvis University, Akpoyubo",
    "Atiba University, Oyo",
    "Augustine University",
    "Ave Maria University, Piyanko",
    "Azman University, Kano",
    "Baba Ahmed University, Kano",
    "Babcock University, Ilishan-Remo",
    "Baze University",
    "Bells University of Technology, Otta",
    "Benson Idahosa University, Benin City",
    "Bingham University, New Karu",
    "Bowen University, Iwo",
    "British Canadian University, Obufu",
    "Caleb University, Lagos",
    "Canadian University of Nigeria, Abuja",
    "Capital City University, Kano",
    "Caritas University, Enugu",
    "Chrisland University",
    "Christopher University, Mowe",
    "Claretian University of Nigeria, Nekede",
    "Clifford University, Owerrinta",
    "Coal City University, Enugu",
    "College of Petroleum and Energy Studies, Kaduna",
    "Cosmopolitan University, Abuja",
    "Covenant University, Ota",
    "Crawford University, Igbesa",
    "Crescent University",
    "Dominican University, Ibadan",
    "Dominion University, Ibadan",
    "Edusoko University, Bida",
    "Edwin Clark University, Kiagbodo",
    "Eko University of Medical and Health Sciences, Ijanikin",
    "El-Amin University, Minna",
    "Elizade University, Ilara-Mokin",
    "Elrazi Medical University, Yargaya",
    "European University of Nigeria, Duboyi",
    "Evangel University, Akaeze",
    "Fountain University, Oshogbo",
    "Franco British International University, Kaduna",
    "Gerar University of Medical Sciences, Imope Ijebu",
    "Glorious Vision University, Ogwa",
    "Godfrey Okoye University, Ugwuomu-Nike",
    "Greenfield University, Kaduna",
    "Gregory University, Uturu",
    "Hallmark University, Ijebu Itele",
    "Havilla University, Nde-Ikom",
    "Hensard University, Toru-Orua",
    "Hezekiah University, Umudi",
    "Hillside University of Science and Technology, Okemisi",
    "Huda University, Gusau",
    "Iconic Open University, Sokoto",
    "Igbinedion University, Okada",
    "James Hope University, Lagos",
    "Jewel University, Gombe",
    "Joseph Ayo Babalola University, Ikeji-Arakeji",
    "Karl-Kumm University, Vom",
    "Khadija University, Majia",
    "Khalifa Isyaku Rabiu University, Kano",
    "Kings University, Ode-Omu",
    "Kola Daisi University, Ibadan",
    "Kwararafa University, Wukari",
    "Landmark University, Omu-Aran",
    "Lead City University, Ibadan",
    "Legacy University, Okija",
    "Lighthouse University, Evbobanosa",
    "Lux Mundi University, Umuahia",
    "Madonna University, Okija",
    "Maduka University, Ekwegbe",
    "Maranatha University, Mgbidi",
    "Margaret Lawrence University, Umunede",
    "Maryam Abacha American University of Nigeria, Kano",
    "McPherson University, Seriki Sotayo",
    "Mercy Medical University, Iwo",
    "Mewar International University, Masaka",
    "Michael & Cecilia Ibru University",
    "Miva Open University, Abuja",
    "Mountain Top University",
    "Mudiame University, Irrua",
    "Muhammad Kamalud University, Kwara",
    "Newgate University, Minna",
    "Nigerian British University, Asa",
    "Nigerian University of Technology and Management, Apapa",
    "Nile University of Nigeria, Abuja",
    "NOK University, Kachia",
    "North Eastern University, Gombe",
    "NorthWest University, Sokoto",
    "Novena University, Ogume",
    "Obong University, Obong Ntak",
    "Oduduwa University, Ipetumodu",
    "Ojaja University, Eiyenkorin",
    "PAMO University of Medical Sciences, Port Harcourt",
    "Pan-Atlantic University, Lagos",
    "Paul University, Awka",
    "PeaceLand University, Enugu",
    "Peter University, Achina-Onneh",
    "Philomath University, Kuje, Abuja",
    "Phoenix University, Agwada",
    "Precious Cornerstone University, Oyo",
    "Prime University, Kuje, Abuja",
    "Rayhaan University, Kebbi",
    "Redeemer's University, Ede",
    "Renaissance University, Enugu",
    "Rhema University, Obeama-Asa",
    "Ritman University, Ikot Ekpene",
    "Saisa University of Medical Sciences and Technology",
    "Salem University, Lokoja",
    "Sam Maris University, Ondo",
    "Shanahan University, Onitsha",
    "Skyline University, Kano",
    "Southwestern University, Oku Owa",
    "Spiritan University, Nneochi",
    "Sports University, Idumuje-Ugboko",
    "Summit University, Offa",
    "Tansian University, Umunya",
    "The Duke Medical University, Calabar",
    "Thomas Adewumi University, Oko-Irese",
    "Topfaith University, Mkpatak",
    "Trinity University, Ogun State",
    "University of Mkar, Mkar",
    "University of Offa, Kwara",
    "University on the Niger, Umunya",
    "Venite University, Iloro-Ekiti",
    "Veritas University, Abuja",
    "Vision University, Ikogbo",
    "Wellspring University, Evbuobanosa",
    "Wesley University, Ondo",
    "West Midlands Open University, Ibadan",
    "Western Delta University, Oghara",
    "Westland University, Iwo",
    "Wigwe University, Isiokpo",
  ],
  "Other": [
    "Other / Not listed",
  ],
};